### PR TITLE
Complete lab2 and lab3

### PR DESCRIPTION
**Pull request by Sosnin-Artur**

### CODE REVIEW

**Comment by Sosnin-Artur** [comment]
@katetushkan

**Review by katetushkan — CHANGES_REQUESTED** [review]
Add html tags on top of ur mockups.

**Comment by katetushkan** [comment]
I don't need ur classes, I need tags. Read ur task carefully before submitting smth. And create a different pr for ur 3rd lab.

**Review by katetushkan — APPROVED** [review]
`7` for the 2nd. Create a different pr for the 3rd.

**Pull request closed without merging**
